-- V1__init_schema.sql (sanitized for Flyway)
-- Base schema without session commands, CREATE DATABASE/USE, or flyway_schema_history. -- Engine/charset kept from original dump.
-- === CORE MASTER TABLES (no FKs first) === 
CREATE TABLE client ( id_client bigint(20) NOT NULL AUTO_INCREMENT, address varchar(255) DEFAULT NULL, dni varchar(255) DEFAULT NULL, email varchar(255) DEFAULT NULL, locality varchar(255) DEFAULT NULL, name varchar(255) DEFAULT NULL, phone_number varchar(255) DEFAULT NULL, status varchar(255) DEFAULT NULL, surname varchar(255) DEFAULT NULL, PRIMARY KEY (id_client) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE family ( id_family bigint(20) NOT NULL AUTO_INCREMENT, type_family varchar(255) DEFAULT NULL, PRIMARY KEY (id_family) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
CREATE TABLE warehouse ( id_warehouse bigint(20) NOT NULL AUTO_INCREMENT, address varchar(255) DEFAULT NULL, location varchar(255) DEFAULT NULL, name varchar(255) DEFAULT NULL, PRIMARY KEY (id_warehouse) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE supplier ( id_supplier bigint(20) NOT NULL AUTO_INCREMENT, address varchar(255) DEFAULT NULL, dni varchar(255) DEFAULT NULL, email varchar(255) DEFAULT NULL, locality varchar(255) DEFAULT NULL, name varchar(255) DEFAULT NULL, name_company varchar(255) DEFAULT NULL, phone_number varchar(255) DEFAULT NULL, status varchar(255) DEFAULT NULL, surname varchar(255) DEFAULT NULL, PRIMARY KEY (id_supplier) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE users ( id bigint(20) NOT NULL AUTO_INCREMENT, email varchar(255) DEFAULT NULL, enabled bit(1) NOT NULL, last_name varchar(255) DEFAULT NULL, name varchar(255) DEFAULT NULL, password varchar(255) NOT NULL, phone varchar(255) DEFAULT NULL, role enum('ROLE_EMPLOYEE','ROLE_OWNER') DEFAULT NULL, username varchar(255) NOT NULL, PRIMARY KEY (id), UNIQUE KEY UKr43af9ap4edm43mmtq01oddj6 (username) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === MATERIAL & RELATIONS === 
CREATE TABLE material ( id_material bigint(20) NOT NULL AUTO_INCREMENT, brand varchar(255) DEFAULT NULL, description varchar(255) DEFAULT NULL, internal_number varchar(255) DEFAULT NULL, measurement_unit varchar(255) DEFAULT NULL, name varchar(255) DEFAULT NULL, price_ars decimal(38,2) DEFAULT NULL, price_usd decimal(38,2) DEFAULT NULL, family_id bigint(20) DEFAULT NULL, version bigint(20) DEFAULT NULL, PRIMARY KEY (id_material), KEY FKcle98sn1165wnc792bpsfb6td (family_id), CONSTRAINT FKcle98sn1165wnc792bpsfb6td FOREIGN KEY (family_id) REFERENCES family (id_family) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE material_supplier ( id_material_supplier bigint(20) NOT NULL AUTO_INCREMENT, delivery_time_days int(11) NOT NULL, price_unit decimal(38,2) NOT NULL, material_id bigint(20) NOT NULL, supplier_id bigint(20) NOT NULL, PRIMARY KEY (id_material_supplier), KEY FKb5gq67f2q7fhalow2acynv5jq (material_id), KEY FKcu1ta6tgw90mpnn7rtt4jooeh (supplier_id), CONSTRAINT FKb5gq67f2q7fhalow2acynv5jq FOREIGN KEY (material_id) REFERENCES material (id_material), CONSTRAINT FKcu1ta6tgw90mpnn7rtt4jooeh FOREIGN KEY (supplier_id) REFERENCES supplier (id_supplier) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === ORDERS & DETAILS === 
CREATE TABLE orders ( id_orders bigint(20) NOT NULL AUTO_INCREMENT, date_create date DEFAULT NULL, date_delivery date DEFAULT NULL, client_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_orders), KEY FK17yo6gry2nuwg2erwhbaxqbs9 (client_id), CONSTRAINT FK17yo6gry2nuwg2erwhbaxqbs9 FOREIGN KEY (client_id) REFERENCES client (id_client) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE order_detail ( id_order_detail bigint(20) NOT NULL AUTO_INCREMENT, price_uni decimal(38,2) NOT NULL, quantity decimal(38,2) NOT NULL, material_id bigint(20) DEFAULT NULL, order_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_order_detail), KEY FKcnoamn7qql09sk4t63ibmeu6a (material_id), KEY FKrws2q0si6oyd6il8gqe2aennc (order_id), CONSTRAINT FKcnoamn7qql09sk4t63ibmeu6a FOREIGN KEY (material_id) REFERENCES material (id_material), CONSTRAINT FKrws2q0si6oyd6il8gqe2aennc FOREIGN KEY (order_id) REFERENCES orders (id_orders) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === STOCK & RESERVATIONS === 
CREATE TABLE stock ( id_stock bigint(20) NOT NULL AUTO_INCREMENT, last_update date DEFAULT NULL, quantity_available decimal(38,2) NOT NULL, material_id bigint(20) NOT NULL, warehouse_id bigint(20) NOT NULL, version bigint(20) DEFAULT NULL, PRIMARY KEY (id_stock), KEY FKf123dh2wb06h2d6fmq4v459sg (material_id), KEY FKjq3xoxdl3pw243p9rnertn8q3 (warehouse_id), CONSTRAINT FKf123dh2wb06h2d6fmq4v459sg FOREIGN KEY (material_id) REFERENCES material (id_material), CONSTRAINT FKjq3xoxdl3pw243p9rnertn8q3 FOREIGN KEY (warehouse_id) REFERENCES warehouse (id_warehouse) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE stock_reservation ( id_reservation bigint(20) NOT NULL AUTO_INCREMENT, expires_at date DEFAULT NULL, quantity decimal(38,2) NOT NULL, reserved_at date DEFAULT NULL, status varchar(20) NOT NULL, version bigint(20) NOT NULL DEFAULT 0, client_id bigint(20) DEFAULT NULL, material_id bigint(20) NOT NULL, order_id bigint(20) DEFAULT NULL, warehouse_id bigint(20) NOT NULL, PRIMARY KEY (id_reservation), KEY FKmcp0a4vhgpnfoc9aix0ss6vh5 (client_id), KEY FKsrj8hsw2v738u6q8rk22ey1kv (material_id), KEY FKkmr3ilm3ma4nx448k1wrbjwgn (warehouse_id), KEY FK_stock_res_order (order_id), CONSTRAINT FK_stock_res_order FOREIGN KEY (order_id) REFERENCES orders (id_orders) ON DELETE SET NULL, CONSTRAINT FKkmr3ilm3ma4nx448k1wrbjwgn FOREIGN KEY (warehouse_id) REFERENCES warehouse (id_warehouse), CONSTRAINT FKmcp0a4vhgpnfoc9aix0ss6vh5 FOREIGN KEY (client_id) REFERENCES client (id_client), CONSTRAINT FKsrj8hsw2v738u6q8rk22ey1kv FOREIGN KEY (material_id) REFERENCES material (id_material) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === DELIVERY & ITEMS === 
CREATE TABLE delivery ( id_delivery bigint(20) NOT NULL AUTO_INCREMENT, delivery_date date DEFAULT NULL, status varchar(255) DEFAULT NULL, order_id bigint(20) DEFAULT NULL, version bigint(20) NOT NULL DEFAULT 0, PRIMARY KEY (id_delivery), KEY FKu4e8rjwmg09vmas3ccjwglso (order_id), CONSTRAINT FKu4e8rjwmg09vmas3ccjwglso FOREIGN KEY (order_id) REFERENCES orders (id_orders) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE delivery_item ( id_delivery_item bigint(20) NOT NULL AUTO_INCREMENT, quantity_delivered decimal(38,2) NOT NULL, unit_price_snapshot decimal(38,2) DEFAULT NULL, version bigint(20) NOT NULL DEFAULT 0, delivery_id bigint(20) NOT NULL, material_id bigint(20) NOT NULL, order_detail_id bigint(20) NOT NULL, warehouse_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_delivery_item), KEY FK56cvume0tkg1ai7j33bsdmlx8 (delivery_id), KEY FKcb90bie6dcs51m6on8ucl0lnt (material_id), KEY FK7td57wgceyreb4689t6484p01 (order_detail_id), KEY FKaefwpw62px1v2qo55706vpjhr (warehouse_id), CONSTRAINT FK56cvume0tkg1ai7j33bsdmlx8 FOREIGN KEY (delivery_id) REFERENCES delivery (id_delivery), CONSTRAINT FK7td57wgceyreb4689t6484p01 FOREIGN KEY (order_detail_id) REFERENCES order_detail (id_order_detail), CONSTRAINT FKaefwpw62px1v2qo55706vpjhr FOREIGN KEY (warehouse_id) REFERENCES warehouse (id_warehouse), CONSTRAINT FKcb90bie6dcs51m6on8ucl0lnt FOREIGN KEY (material_id) REFERENCES material (id_material) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === SALES === 
CREATE TABLE sale ( id_sale bigint(20) NOT NULL AUTO_INCREMENT, date_sale date DEFAULT NULL, client_id bigint(20) DEFAULT NULL, delivery_id bigint(20) DEFAULT NULL, order_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_sale), KEY FKon0o9ba5ajsnwivekhl1tfjiy (client_id), KEY FK7p2j8vc94xlupnnjejljda3ee (delivery_id), KEY FK5y9wxb528egrbqjw9xssv577m (order_id), CONSTRAINT FK5y9wxb528egrbqjw9xssv577m FOREIGN KEY (order_id) REFERENCES orders (id_orders), CONSTRAINT FK7p2j8vc94xlupnnjejljda3ee FOREIGN KEY (delivery_id) REFERENCES delivery (id_delivery), CONSTRAINT FKon0o9ba5ajsnwivekhl1tfjiy FOREIGN KEY (client_id) REFERENCES client (id_client) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE sale_detail ( id_sale_detail bigint(20) NOT NULL AUTO_INCREMENT, price_uni decimal(38,2) NOT NULL, quantity decimal(38,2) NOT NULL, delivery_id bigint(20) DEFAULT NULL, material_id bigint(20) NOT NULL, sale_id bigint(20) NOT NULL, PRIMARY KEY (id_sale_detail), KEY FKqbtujgk9ovlk20sjik5dqd54h (delivery_id), KEY FKe5m82ya2k28ol39d2o5o15ddb (material_id), KEY FKgnpg9v1mvi1nyhc18vdcyuh98 (sale_id), CONSTRAINT FKe5m82ya2k28ol39d2o5o15ddb FOREIGN KEY (material_id) REFERENCES material (id_material), CONSTRAINT FKgnpg9v1mvi1nyhc18vdcyuh98 FOREIGN KEY (sale_id) REFERENCES sale (id_sale), CONSTRAINT FKqbtujgk9ovlk20sjik5dqd54h FOREIGN KEY (delivery_id) REFERENCES delivery (id_delivery) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE payment ( id_payment bigint(20) NOT NULL AUTO_INCREMENT, amount decimal(38,2) DEFAULT NULL, date_payment date DEFAULT NULL, method_payment varchar(255) DEFAULT NULL, status varchar(255) DEFAULT NULL, sale_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_payment), KEY FKdngfmp98cmoa6nlcao8qijthg (sale_id), CONSTRAINT FKdngfmp98cmoa6nlcao8qijthg FOREIGN KEY (sale_id) REFERENCES sale (id_sale) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === PURCHASES === 
CREATE TABLE purchase ( id_purchase bigint(20) NOT NULL AUTO_INCREMENT, date_purchase date DEFAULT NULL, supplier_id bigint(20) DEFAULT NULL, PRIMARY KEY (id_purchase), KEY FK8omm6fki86s9oqk0o9s6w43h5 (supplier_id), CONSTRAINT FK8omm6fki86s9oqk0o9s6w43h5 FOREIGN KEY (supplier_id) REFERENCES supplier (id_supplier) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE purchase_detail ( id_purchase_detail bigint(20) NOT NULL AUTO_INCREMENT, purchased_price decimal(38,2) NOT NULL, quantity decimal(38,2) NOT NULL, material_supplier_id bigint(20) NOT NULL, purchase_id bigint(20) NOT NULL, PRIMARY KEY (id_purchase_detail), KEY FK5q7ljiqbndxy9r1ovf7ea5kqr (material_supplier_id), KEY FK65hoe4yy1817l2vm74msb8eq5 (purchase_id), CONSTRAINT FK5q7ljiqbndxy9r1ovf7ea5kqr FOREIGN KEY (material_supplier_id) REFERENCES material_supplier (id_material_supplier), CONSTRAINT FK65hoe4yy1817l2vm74msb8eq5 FOREIGN KEY (purchase_id) REFERENCES purchase (id_purchase) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === AUDIT (legacy simple table present in dump) === 
CREATE TABLE audit ( id_audit bigint(20) NOT NULL AUTO_INCREMENT, action varchar(255) NOT NULL, change_date datetime(6) NOT NULL, changed_by varchar(255) NOT NULL, new_value varchar(1000) DEFAULT NULL, old_value varchar(1000) DEFAULT NULL, record_id bigint(20) NOT NULL, table_name varchar(255) NOT NULL, PRIMARY KEY (id_audit) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === AUDIT 2.0 (event + detail) === 
CREATE TABLE audit_event ( id bigint(20) NOT NULL AUTO_INCREMENT, timestamp datetime(6) NOT NULL, actor_id bigint(20) DEFAULT NULL, actor_name varchar(200) NOT NULL, roles varchar(255) DEFAULT NULL, ip varchar(255) DEFAULT NULL, user_agent varchar(255) DEFAULT NULL, request_id varchar(255) DEFAULT NULL, action varchar(80) NOT NULL, entity varchar(120) NOT NULL, entity_id bigint(20) DEFAULT NULL, status varchar(20) NOT NULL, message varchar(500) DEFAULT NULL, PRIMARY KEY (id), KEY idx_audit_event_time (timestamp), KEY idx_audit_event_entity (entity,entity_id), KEY idx_audit_event_action (action), KEY idx_audit_event_ts (timestamp), KEY idx_audit_event_actor (actor_name), KEY idx_audit_event_ent_id (entity,entity_id), KEY idx_audit_event_status (status) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
CREATE TABLE audit_detail ( id bigint(20) NOT NULL AUTO_INCREMENT, event_id bigint(20) NOT NULL, diff_json longtext DEFAULT NULL, old_json longtext DEFAULT NULL, new_json longtext DEFAULT NULL, PRIMARY KEY (id), KEY fk_auditdetail_event (event_id), CONSTRAINT fk_auditdetail_event FOREIGN KEY (event_id) REFERENCES audit_event (id) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci; 
-- === STOCK MOVEMENTS (no FKs, indexed) === 
CREATE TABLE stock_movement ( id bigint(20) NOT NULL AUTO_INCREMENT, timestamp datetime(6) NOT NULL, material_id bigint(20) NOT NULL, material_name varchar(255) NOT NULL, warehouse_id bigint(20) NOT NULL, warehouse_name varchar(255) NOT NULL, from_qty decimal(19,3) NOT NULL, to_qty decimal(19,3) NOT NULL, delta decimal(19,3) NOT NULL, reason varchar(40) NOT NULL, source_type varchar(40) DEFAULT NULL, source_id bigint(20) DEFAULT NULL, user_id bigint(20) DEFAULT NULL, user_name varchar(255) DEFAULT NULL, note varchar(500) DEFAULT NULL, request_id varchar(255) DEFAULT NULL, PRIMARY KEY (id), KEY idx_stockmov_time (timestamp), KEY idx_stockmov_mat (material_id), KEY idx_stockmov_wh (warehouse_id), KEY idx_stockmov_reason (reason), KEY idx_stockmov_source (source_type,source_id), KEY idx_sm_ts (timestamp), KEY idx_sm_mat_wh (material_id,warehouse_id), KEY idx_sm_reason (reason), KEY idx_sm_user (user_name) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
